// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfwapkdaxjtgwbncwynp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmd2Fwa2RheGp0Z3dibmN3eW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTc0OTAsImV4cCI6MjA3MzYzMzQ5MH0.av0228UrPoRATjpeLzApKXg1UZXF0GJT68HVRk19Ta8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});